nelmio_api_doc:
    areas:
        default:
            path_patterns:
                - ^/api(?!/docs)
    documentation:
        info:
            title: PiposDocuments Core API
            description: Core API for PiposDocuments
            version: 1.0.0
        components:
            schemas:
                Error:
                    type: object
                    properties:
                        error:
                            type: string
