<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260410120000 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'Create messenger_messages table for the Doctrine failed transport';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750
                ON messenger_messages (queue_name, available_at, delivered_at, id)
            SQL);
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        $this->addSql(
            <<<'SQL'
DROP TABLE IF EXISTS messenger_messages
SQL);
    }
}
